sudo: false
language: scala
stages:
  - test
  - name: deploy
    if: branch = master AND NOT type IN (pull_request)

script: sbt +test

jobs:
  include:
    - stage: test
      jdk: oraclejdk8
    - stage: test
      jdk: openjdk8
      script: sbt clean coverage +test && sbt coverageReport coveralls
    - stage: deploy
      jdk: openjdk8
      script: |
        openssl aes-256-cbc -K $encrypted_15ce06f7b2e5_key -iv $encrypted_15ce06f7b2e5_iv -in travis/secrets.tar.enc -out travis/local.secrets.tar -d &&
          tar xv -C travis -f travis/local.secrets.tar &&
          sbt +releaseEarly
env:
  global:
    - secure: "e/Doy2GpbQxUUdJ/51wlBs+WSiozVSyuGjzo+kr8hp7h6Qa5dEmsUi82jShrs2fDVW27Ivmph08Yr4JnosWlkrW08Hz1tFrXDdauDXSwBkL54wdcriUWWKDmhtJ10y6NfB5xhU2xph+kUM04oT5v3EsN5adrIg7VkSDP12k8PPR1Aup4AR9cyI3kWkkK4IP13XMMam/p0cXrSDH20KJbDONFG3yjP1YN34TGlC/D6i1TvIP5+GEPR0oX4YMAHw8vZHCIokslSpjcegOQxLVP58SC8v4WIBIJ/D6Z24itBzQrrp4IhCIXUVp+Y2JE4nVSAXWVKuP7bs/NY+U7zr5GJVD7nE6m2YmEkjV/Q8dFhemIYLgPSDW7uAo8vpC8J76C0CA/+59nKNrmXRz4JqnH6FQbBfU2tpFztG/iiTG3fuV8WMjTMmiyyCuFrFqPUwA47f5vMOSyHdQc7hkhyARch1XV+o8bflNaJbv18lOuuKvx5eVyZzcAyrDf20ZFqVdC+K2hfYHaknCvPXQdysfz6Go36Q6ls7Z3tOSYKtN8rtTk5d1CivpGrkjcQ7SMOT1UP/iR/qVYdrkuJkWLN/HJXWLisBpns6w0bROoa0wSrzHeZxzuoPvghO2BjVqAGUUSd8Er++HYSjhFZY5Bp5vm4CEyP2DB/B7jgF8QSS3pj9o="
    - secure: "KmZnQi4kLfXBT7mMM9UYPicO4s3Oi4LA13JkF0QXIgudV/ZYoOHz4gQdbTlq2ryml8NsypjiTfsNlxu1LQ83ay+kbQF9CZWkWCAigA02vtzZGHQclZ9T8EWQSCblqaSq+JHtNSpC67DMTTwIriF+KXAZ9aM8I8UQtRVxS5CgCu+ztYYxjZZECHN5GdKaTnHC75wEHYG/umvDKCYIE1Qe7ms23DQy9s7N0c4j3HBbzEYgntmEOc1UYNBKpQUBWUUeQC9a1kN0AmxNIDSkdq05d8Wgwq2pueTo9t26H++XWmy69GjVkF5kLMNPJqHCNO6nUTMp/+CWiagFl/nI49tBV9Wh228uEoUpBBYAlm2Sr4faKBj5HgeJgMMK+OzC+uCNEwhxjpAwYT57yFEen0MAiChy77r5FOQkyMhdlkju7XcuKsdwg8xP8PoL1HxiHTsdNtZVmk0hT8zBYVKz8eMjlY3TXr6vWj0KDyBOsy2+iWQ9h5aRPYPojn4nZBN+Xr6+WIpX36Vt39qZmnq47aq7OQGa3y0Zgazf7ganUmHqJ+6IbcwTfwbCBN85MdoBzOvrmj4W7zNtv1xP7cgmWfSgR8XyB4vE4va3YxhloaYZipuprq+Yh22bXrDn84yv7ag8bdJD8cwV7AFxVOPuFTfZ4i/vgbRkXXH+g0v9tyZbC/8="
    - secure: "Rq06eYE55d6ptYp/oqBsPvVOTKBlcpR08/ZHpO0tSDHTOEJNVf+K2K5FUSErdYLuIlIuonpG1kcJ98QtaR9vFUXCb7g3RGrq7qDyYQ4uF5LH5vPp40RxagysNrs2nrmzeqOdvjFA2Ut2JuxrvfgsZbxObpPoQXwrJm1YskCezTvQ3vJrRElI5HpEvMjDz5xsHBVFwccnd1VyPsUgP6GLGcEJGCIktuHe4Yof+siRRsNmyra9npxpgPNdaKZr1seX2DBvDl9XTJqz4l0NinUI2bUVVTNPPxob0GUuXPB96Leo4qzeFwq+x5F2QmChu8/a42NNojI8h9ji16chLeCtD7KAYnwTQaZB70KlwYKfw+S/NXIlnDFDliBFoNKQVUYl1eihCdcHwOaIgo3XEtrNxhiOJW60goB8ymfC9zktCDZd8bLzk73fNQhmZ9SMPixD8sFXLy8m125jsTMy6uYD7yuMPzoVbCKaDpNwVm/HlpcWDxs/2NnNqVmDCUyQsyF8ywhN03lgTf6I8Qv0hjCbIHhAaW4Ldp6tZC46LPUP7htzm9zzv9jarxlmEBr7ttNM29GiPXi/7oCzaoeqWQJxACYkMNbwtK7UuY7AmMJGlmmYmuYSzc7ZUYHH0wOa3Jd2AnUu2psq3UMee9Ly+xwSOnEgUDK2sslO2Biz9feFtZY="